### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by barnettjacob** [minrk/nbextension-scratchpad#1]
Sorry, pretty sure this is my issue not yours :-)

I'm on OSX and although installation seems to go OK, I get this error when I try to enable the add-in:

`Traceback (most recent call last):
  File "/Users/jb/Library/Jupyter/nbextensions/nbextension-scratchpad/enable", line 10, in <module>
    from notebook.services.config import ConfigManager as FrontendConfigManager
ImportError: No module named notebook.services.config
`

I entered the code 'verbatim' from the readme - was this the right thing to do?
Thanks
Jacob

**Comment by minrk** [comment]
What do you get from `head $(which jupyter-notebook)`?

**Comment by minrk** [comment]
...and `which python`

**Comment by barnettjacob** [comment]
I get 

```
jb> head $(which jupyter-notebook)
#!/Users/jb/anaconda/bin/python
if __name__ == '__main__':
    import sys
    import notebook.notebookapp

    sys.exit(notebook.notebookapp.main())
```

And

```
jb> which python
/usr/bin/python
```

Although that's not the python I use
Thanks.

**Comment by junpenglao** [comment]
same problem here. I got the same error message of "no module named... ". And my output is

```
laoj:~$ head $(which jupyter-notebook)
#!/usr/bin/python3

# -*- coding: utf-8 -*-
import re
import sys

from notebook.notebookapp import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
```

```
laoj:~$ which python
/usr/bin/python
```

Also not the python I use

**Comment by junpenglao** [comment]
OK i manage to do it by changing the python in the enable file.

**Comment by minrk** [comment]
If `python` isn't the Python that has Jupyter, you can run the script with that Python explicitly:

```
/path/to/notebook-having/python "$(jupyter --data-dir)/nbextensions/nbextension-scratchpad/enable"
```

**Comment by barnettjacob** [comment]
Thanks. So when I try `/Users/jb/anaconda/bin/jupyter-notebook "$(jupyter --data-dir)/nbextensions/nbextension-scratchpad/enable"` I seem to make progress, the usual notebook messages appear in my terminal and 'files/enable' opens in my browser. 

I don't however see the button when I open a notebook.
Thanks.

**Comment by minrk** [comment]
Sorry, it shouldn't be the `jupyter-notebook` executable, it should be the same _Python_ that is used there. In your case, it would be:

```
/Users/jb/anaconda/bin/python
```

and for @junpenglao it would be:

```
/usr/bin/python3
```

**Comment by barnettjacob** [comment]
Awesome. That's it! 
Thank you.

**Comment by minrk** [comment]
I forgot about the public API for this, so I've just removed the enable script. You can enable with:

```
jupyter nbextension enable nbextension-scratchpad/main
```

which shouldn't have any path issues.

**Comment by junpenglao** [comment]
awesome! thanks a lot

**Comment by barnettjacob** [comment]
Superb. Thanks.
