### ISSUE TITLE
Shift + Enter executes cells in main notebook even when scratchpad is open

### ISSUE THREAD

**Issue by op1490** [minrk/nbextension-scratchpad#13]
This could be really useful but mostly (it sometimes seems to work) my 'run cell' command just runs the cells in the main notebook, even when the scratchpad is open. might be nice to have the option to change the scratchpad run command to avoid any interference? or

**Comment by rosenfeldamir** [comment]
I am also facing this issue. Anyone else? any solution?

**Comment by DrJimFan** [comment]
When I use `jupyter-vim` mode, this happens all the time: whatever I type in the box and "shift-enter", it executes the cell in the main notebook instead of the cell in scratchpad's focus. 
Would love to know how to fix it!

**Comment by lbollar** [comment]
I am also a jupyter-vim user and have this same problem. Guessing something in the vim modes is overriding the scratchpad.

**Comment by Melkiades** [comment]
I found a solution for my case (I use sublime shortcuts, but it works also with vim ones)!
It was conflicting with the following nbextension:

> Navigation-Hotkeys

Untoggle that option and it should work again.
