### ISSUE TITLE
Shortcut key modification

### ISSUE THREAD

**Issue by ky0on** [minrk/nbextension-scratchpad#20]
How can I change the shortcut keys for scratchpad?
I want to launch the scratchpad with `Cmd+b`.

**Comment by alvitawa** [comment]
Ctrl+B is a bit unfortunate for firefox, as it is also used as the (useless to me) shortcut for bookmarks. The plugin does seem to override it most of the time but not always for some reason. The firefox shortcut cannot be changed.

Shortcut key modification would be a solution.

**Comment by ky0on** [comment]
Updated `~/.jupyter/nbconfig/notebook.json`.

```json
{
  "keys": {
    "command": {
      "bind": {
        "cmd-b": "auto:scratchpad-toggle"
      }
}
```
